/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  * 
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "stdio.h"

#include <string.h> // Required to use strlen()
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
ADC_HandleTypeDef hadc;

TIM_HandleTypeDef htim2;
TIM_HandleTypeDef htim3;
TIM_HandleTypeDef htim4;

UART_HandleTypeDef huart2;

/* USER CODE BEGIN PV */

enum modos{MANUAL, AUTOMATICO};
volatile enum modos modo = AUTOMATICO;   // Start in automatic mode
volatile char flag_modo;
volatile char flag_medir;
uint32_t valor_adc;




uint32_t tiempo_inicio_echo = 0;
uint32_t tiempo_echo = 0;
uint8_t flag_distancia = 0;





volatile uint8_t posicion_actual = 0;  // Current sweep position index
volatile uint8_t flag_2segs = 0;      // Set every 2 seconds

volatile uint8_t barrido_activo = 0;
// Servo PWM compare values calibrated with the potentiometer
uint16_t posiciones[5] = {500, 1000, 1500, 2000, 2500};  // -90°, -45°, 0°, 45°, 90°

volatile uint8_t pendiente_manual = 0;





char texto[100];                    // USART transmission buffer
uint32_t array_distancias[5] = {0}; // Stores the five distance measurements from the sweep


/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_ADC_Init(void);
static void MX_TIM4_Init(void);
static void MX_TIM3_Init(void);
static void MX_TIM2_Init(void);
/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */



// EXTI13 handler: mode selection button on PC13
// Sets a flag when the button interrupt is triggered
void EXTI15_10_IRQHandler(void){
  if((EXTI->PR & 0x2000)!= 0){ // Check that the interrupt was generated by EXTI13
    flag_modo = 1;
    EXTI -> PR = 0x2000; // Clear pending flag
  }
}

// EXTI4 handler: measurement button on PB4
void EXTI4_IRQHandler(void){
  if((EXTI->PR & 0x0010)!= 0){
    flag_medir = 1;  // Falling edge on PB4: set flag_medir so the main loop starts a measurement
    EXTI -> PR = 0x0010; // Clear pending flag
  }
}


void TIM4_IRQHandler(void) {

	// Channel 1
    if ((TIM4->SR & 0x0002) != 0) {    // CCR1: 0.5 s timeout to turn off the measurement LED
        GPIOB->BSRR |= (1<<(5+16));    // Turn off LED
        TIM4->SR &= ~0x0002;
        // In manual mode, stop the counter; in automatic mode, keep it running until the 2 s event
        if (modo == MANUAL) {
            TIM4->CR1 &= ~0x0001;
            TIM4->CNT = 0;
        }
    }
    // Channel 2
    if ((TIM4->SR & 0x0004) != 0) {    // CCR2: 2 s timeout to move to the next servo position
        flag_2segs = 1;                // Indicates that 2 seconds have elapsed since the last measurement
        TIM4->SR &= ~0x0004;
        TIM4->CR1 &= ~0x0001;          // Stop until the main loop restarts it
        TIM4->CNT = 0;
    }
}


void TIM3_IRQHandler(void) {

	// Channel 3: after 10 us, drive the trigger pin low
	if ((TIM3->SR & 0x0008) != 0) {
	   GPIOC->BSRR |= (1 << (8+16));  // PC8 = 0
	   TIM3->DIER &= ~(0x0008);       // Disable channel 3 interrupt until the next measurement
	   TIM3->SR &= ~(0x0008);         // Clear channel 3 flag
	}
	// Channel 4: echo input capture
	// Captures the rising edge when the echo signal goes high
	// Captures the falling edge when the echo signal goes low
    if ((TIM3->SR & 0x0010) != 0) {
    	uint16_t captura = TIM3->CCR4;
    	if (captura < 0){
    		captura = captura + 0xFFFF;
    	}

        if ((GPIOC->IDR & (1 << 9)) != 0) {   // Rising edge: echo is high
            tiempo_inicio_echo = captura;
        } else {                                  // Falling edge: echo is low
            tiempo_echo = (captura - tiempo_inicio_echo);
            flag_distancia = 1;
        }

        TIM3->SR &= ~(0x0010);   // Clear flags

    }
}



/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_USART2_UART_Init();
  MX_ADC_Init();
  MX_TIM4_Init();
  MX_TIM3_Init();
  MX_TIM2_Init();
  /* USER CODE BEGIN 2 */

  ///////////////////////// PA5 OUTPUT (01) y PC13 INPUT (00) //////////////////////

  // Mode indicator LED
  GPIOA -> MODER &= ~(1 << (5*2 + 1));
  GPIOA -> MODER |=  (1 << (5*2));

  // Mode selection button
  GPIOC -> MODER &= ~(1 << (13*2 + 1));
  GPIOC -> MODER &= ~(1 << (13*2));

  ///////////////////////// PB5 OUTPUT (01) y PB4 INPUT (00) //////////////////////

  // External measurement indicator LED
  GPIOB -> MODER &= ~(1 << (5*2 + 1));
  GPIOB -> MODER |=  (1 << 5*2);

  // Measurement start button
  GPIOB -> MODER &= ~(1 << (4*2 + 1));
  GPIOB -> MODER &= ~(1 << (4*2));



  // ---- PB4 pull-up configuration ----

  // Configure pull-up so the button uses a falling edge, like the Nucleo PC13 button
  // With pull-down, the EXTI configuration would need a rising edge instead
  // With pull-up, the pin is high in idle state and low when pressed
  GPIOB -> PUPDR &= ~(1 << (4*2+1));
  GPIOB -> PUPDR |= (1 << (4*2));

  // ---- PA1 analog input for ADC potentiometer ----

  GPIOA -> MODER |= (1<<(1*2));
  GPIOA -> MODER |= (1<<(1*2+1));

  // ---- PC8 trigger output ----

  GPIOC->MODER &= ~(1 << (8*2 + 1));
  GPIOC->MODER |=  (1 << (8*2));     // Output mode
  GPIOC->BSRR  |=  (1 << (8+16));    // PC8 = 0

  // ---- PC9 alternate function: echo input on TIM3_CH4 ----

  GPIOC->MODER &= ~(1 << (9*2));
  GPIOC->MODER |=  (1 << (9*2 + 1));     // Alternate function mode

  GPIOC->AFR[1] &= ~(0xF << (1*4));   // Clear previous AF configuration
  GPIOC->AFR[1] |=  (0x2 << (1*4));   // Select AF2

  // ---- PC0-PC4 distance indicator LEDs ----

  // PC0 output
  GPIOC->MODER |=  (1 << (0*2));
  GPIOC->MODER &= ~(1 << (0*2+1));

  // PC1 output
  GPIOC->MODER |=  (1 << (1*2));
  GPIOC->MODER &= ~(1 << (1*2+1));

  // PC2 output
  GPIOC->MODER |=  (1 << (2*2));
  GPIOC->MODER &= ~(1 << (2*2+1));

  // PC3 output
  GPIOC->MODER |=  (1 << (3*2));
  GPIOC->MODER &= ~(1 << (3*2+1));

  // PC4 output
  GPIOC->MODER |=  (1 << (4*2));
  GPIOC->MODER &= ~(1 << (4*2+1));

  // Turn all LEDs off at startup
  GPIOC->BSRR |= (1 << 16);  // PC0 = 0
  GPIOC->BSRR |= (1 << 17);  // PC1 = 0
  GPIOC->BSRR |= (1 << 18);  // PC2 = 0
  GPIOC->BSRR |= (1 << 19);  // PC3 = 0
  GPIOC->BSRR |= (1 << 20);  // PC4 = 0

  // ---- PA0 AF1: TIM2_CH1 PWM output ----

  GPIOA->MODER &= ~(1 << (0*2));
  GPIOA->MODER |=  (1 << (0*2 + 1));

  GPIOA->AFR[0] &= ~(0xF << (0*4));
  GPIOA->AFR[0] |=  (0x1 << (0*4));   // AF1: TIM2_CH1

  // ---- EXTI configuration for PC13 ----

  // Falling edge trigger
  SYSCFG->EXTICR[3] = 0x0020;   // Map EXTI13 to GPIOC
  EXTI->RTSR &= ~(0x01 <<13);   // Disable rising edge trigger
  EXTI->FTSR |=  (0x01 <<13);   // Enable falling edge trigger
  EXTI->IMR  |=  (0x01 <<13);   // Enable EXTI line

  NVIC -> ISER[1] |= (1<<8);    // NVIC position 40: EXTI lines 10 to 15

  // ---- EXTI configuration for PB4 ----

  // Falling edge trigger
  SYSCFG->EXTICR[1] = 0x0001;   // Map EXTI4 to GPIOB
  EXTI->RTSR &= ~(0x01 <<4);    // Disable rising edge trigger
  EXTI->FTSR |= (0x01 <<4);     // Enable falling edge trigger
  EXTI->IMR |= (0x01 <<4);      // Enable EXTI line

  NVIC -> ISER[0] |= (1<<10);    // NVIC position 10

  // ---- ADC manual configuration: continuous mode, channel 1 on PA1 ----

  ADC1->CR2 &= ~(0x00000001);    // ADON = 0 before configuration
  ADC1->CR1 = 0x00000000;        // RES = 00: 12-bit resolution; SCAN = 0; EOCIE = 0
  ADC1->CR2 = 0x00000412;        // EOCS = 1, DELS = 001, CONT = 1: continuous conversion

  ADC1->SQR1 = 0x00000000;       // One channel in the sequence
  ADC1->SQR5 = 0x00000001;       // AIN1 channel on PA1

  ADC1->CR2 |= 0x00000001;       // ADON = 1: enable ADC
  while((ADC1->SR & 0x0040)==0); // Wait until ADONS = 1
  ADC1->CR2 |= 0x40000000;       // SWSTART = 1: start continuous conversion

  // ---- TIM4 output compare for measurement LED timing ----

  TIM4->CR1  = 0x0000;   // ARPE = 0, CEN = 0: counter stopped
  TIM4->CR2  = 0x0000;
  TIM4->SMCR = 0x0000;

  TIM4->PSC  = 31999;    // 32 MHz / 32000 = 1000 counts/s, so 1 count = 1 ms
  TIM4->CNT  = 0;        // Initialize counter to 0
  TIM4->ARR  = 0xFFFF;   // Output compare timer period
  TIM4->CCR1 = 500;      // 500 counts = 0.5 s
         	   	   	   	 // Interrupt is generated when the counter reaches this value

  // TIM4->CCR2 is set only in automatic mode

  TIM4->DIER  = 0x0006;  // Enable channel 1 and channel 2 interrupts
  TIM4->CCMR1 = 0x0000;  // CCyS = 0: output compare; no hardware output is used
  TIM4->CCER  = 0x0000;  // Disable hardware output

  // Do not start the counter here; it starts when the measurement button is pressed
  // The timer is started later from the flag_medir block
  TIM4->EGR |= 0x0001;
  TIM4->SR   = 0;        // Clear flags

  NVIC->ISER[0] |= (1 << 30); // TIM4 NVIC position is 30



  // ---- TIM3 input capture for echo and output compare for trigger ----

  TIM3->CR1  = 0x0000;   // ARPE = 0, CEN = 0
  TIM3->CR2  = 0x0000;
  TIM3->SMCR = 0x0000;

  TIM3->PSC  = 31;       // 32 MHz / 32 = 1 MHz, so 1 count = 1 us
  TIM3->CNT  = 0;
  TIM3->ARR  = 0xFFFF;

  // Channel 3 compare value for trigger pulse
  TIM3->CCR3  = 10;      // 10 counts = 10 us
            	  	   	 // Interrupt is generated when the counter reaches this value

  // CCR4 is used by input capture to store PC9 rising and falling edge timestamps

  // Channel interrupts are enabled only when a new measurement starts
  // This avoids starting input capture immediately after reset
  // The echo capture is therefore enabled only after pressing the measurement button


  TIM3->CCMR2 = 0x0100;  // CC3S = 00: output compare on channel 3
            	      	 // CC4S = 01: input capture on channel 4
                         // IC4F = 0000: no input filter
                         // IC4PSC = 00: no prescaler

  TIM3->CCER  = 0xB000;  // CC4NP:CC4P = 11: capture both edges
                         // CC4E = 1: capture enabled
            	   	   	 // Channel 3 uses output compare without hardware output; PC8 is controlled with BSRR

  TIM3->EGR |= 0x0001;   // Generate update event
  TIM3->SR   = 0;        // Clear flags
  //TIM3->CR1 |= 0x0001;   // Start timer if input capture is intentionally enabled at startup

  NVIC->ISER[0] |= (1 << 29); // TIM3 NVIC position is 29




  // ---- TIM2 PWM channel 1 for servo control ----

  TIM2->CR1  = 0x0080;   // ARPE = 1: preload enabled for PWM
  TIM2->PSC  = 31;       // 32 MHz / 32 = 1 MHz, so 1 count = 1 us
  TIM2->ARR  = 19999;    // 20,000 counts * 1 us = 20 ms PWM period
  TIM2->CCR1 = 1500;     // Center position

  TIM2->CCMR1 = 0x0068;  // OC1M = 110: PWM mode 1; CC1S = 00: output
  TIM2->CCER  = 0x0001;  // CC1E = 1: output enabled on PA0

  TIM2->EGR  |= 0x0001;
  TIM2->SR    = 0;
  TIM2->CR1  |= 0x0001;  // Start timer




  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */

  while (1)
  {
	  // Reset runtime flags and variables
	      flag_modo = 0;   // Mode selection flag
	      flag_medir = 0;  // Measurement request flag
	      flag_distancia = 0; // Distance-ready flag
	      tiempo_echo = 0;
	      GPIOA -> BSRR |= (1<<(5)); // Turn on LED
	      int16_t angulo_anterior = -1;


	      sprintf(texto, "RESETEO: Empezamos en modo automático\r\n");
	      HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);


	      while (1)
	      {
	        // Mode selection
	        if(flag_modo == 1){  // The interrupt handler sets flag_modo when the button is pressed
	          flag_modo = 0;     // Clear flag

	          if(modo == AUTOMATICO){
	        	  // If the sweep is running, delay the mode change
	        	  if(barrido_activo == 1){
	        		  pendiente_manual = 1;  // Store pending request to switch to manual mode
	        	      sprintf(texto, "Cambio a Manual pendiente\r\n");
	        	      HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
	        	  }
	        	  // If no sweep is running, switch directly to manual mode
	        	  else{
	        	      modo = MANUAL;
	        	      GPIOA->BSRR |= (1<<(5+16));
	        	      sprintf(texto, "Manual\r\n");
	        	      HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
	        	  }
	          }
	          else{
	            modo = AUTOMATICO;
	            TIM2->CCR1 = 1500; // Return servo to the center when switching to automatic mode
	            // Mode LED on in automatic mode
	            GPIOA -> BSRR |= (1<<(5));
	            sprintf(texto, "Automático\r\n");
	            HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
	          }
	        }

	        if(flag_medir == 1){
	            flag_medir = 0;

	            // Measurement LED controlled for 0.5 s using TIM4
	            GPIOB->BSRR |= (1<<(5)); // Turn on LED

	            TIM4->CNT   = 0;
	            TIM4->EGR  |= 0x0001; // Generate update event
	            TIM4->SR    = 0;

	            TIM4->CCR1 = 500;     // 0.5 s for the measurement LED
	            //TIM4->DIER |= 0x0004; // Enable CCR2 interrupt if needed

	            if (modo == AUTOMATICO) {
	            	barrido_activo = 1;            // Activate sweep when measurement starts in automatic mode
	                posicion_actual = 0;           // Reset sweep position index
	                TIM4->CCR2 = 2000;             // 2 s before moving to the next servo position
	                TIM2->CCR1 = posiciones[posicion_actual];    // Move servo to the first sweep position
	            }

	            TIM4->CR1 |= 0x0001;



	            // ---- Ultrasonic measurement using TIM3 ----

	            // Start a new measurement every time the button is pressed
	            TIM3->CR1 &= ~0x0001; // Stop counter before restarting
	            TIM3->CNT = 0;        // Reset counter

	            GPIOC->BSRR |= (1<<8);  // Trigger high

	            // Enable interrupts only when a measurement starts
	            TIM3->DIER |= 0x0008;   // Channel 3
	            TIM3->DIER |= 0x0010;   // Channel 4
	            TIM3->SR = 0;

	            // Start the timer after configuring a new measurement
	            TIM3->CR1 |= 0x0001; // Start counter

	            sprintf(texto, "Está midiendo\r\n");
	            HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
	        }

		    if (flag_distancia == 1){

		        flag_distancia = 0;

		        // Sound travels at approximately 0.034 cm/us and the echo is a round trip
		        uint32_t distancia = (tiempo_echo * 0.034) / 2;  // Distance in cm

		        if (modo == MANUAL) {
		        	// Print result immediately
		        	sprintf(texto, "Modo manual -> distancia: %ld cm\r\n", distancia);
		        	HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
		        }
		        else {
		        	// Automatic mode: store the measurement for the current sweep position
		        	array_distancias[posicion_actual] = distancia;
		        }

		        // Turn all distance LEDs off before updating them
		        GPIOC->BSRR |= (1 << 16);
		        GPIOC->BSRR |= (1 << 17);
		        GPIOC->BSRR |= (1 << 18);
		        GPIOC->BSRR |= (1 << 19);
		        GPIOC->BSRR |= (1 << 20);

		        // Turn on LEDs according to the measured distance
		        // Independent thresholds allow several LEDs to be active at the same time
		        if (distancia < 80) GPIOC->BSRR |= (1 << 0);
		        if (distancia < 60) GPIOC->BSRR |= (1 << 1);
		        if (distancia < 40) GPIOC->BSRR |= (1 << 2);
		        if (distancia < 20) GPIOC->BSRR |= (1 << 3);
		        if (distancia < 10) GPIOC->BSRR |= (1 << 4);
		    }

		    if (flag_2segs == 1 && modo == AUTOMATICO && barrido_activo == 1) {

		        flag_2segs = 0;

		        // Continue the sweep until the last servo position is reached
		        if (posicion_actual < 4) {
		        	posicion_actual++;
		            TIM2->CCR1 = posiciones[posicion_actual];  // Move servo to the next position

		            GPIOB->BSRR |= (1<<5);  // Turn on LED
		            TIM4->CNT = 0;
		            TIM4->CCR2 = 2000;      // Set TIM4 channel 2 timeout before restarting the counter
		            TIM4->CCR1 = 500;       // Set TIM4 channel 1 timeout before restarting the counter
		            TIM4->SR = 0;
		            TIM4->CR1 |= 0x0001;    // Start TIM4



		            // Ultrasonic trigger sequence
		            TIM3->CR1 &= ~0x0001;   // Stop counter
		            TIM3->CNT = 0;
		            GPIOC->BSRR |= (1<<8);  // Set trigger high
		            TIM3->DIER |= 0x0008;   // Enable channel 3 interrupt
		            TIM3->DIER |= 0x0010;   // Enable channel 4 interrupt
		            TIM3->SR = 0;
		            TIM3->CR1 |= 0x0001;    // Start counter
		        }
		        else {
		            TIM2->CCR1 = 1500;     // Return servo to the center

		            // Sweep finished: print all stored measurements
		            sprintf(texto, "Modo automatico -> distancia: [%ld, %ld, %ld, %ld, %ld] cm\r\n", array_distancias[0], array_distancias[1], array_distancias[2], array_distancias[3], array_distancias[4]);
		            HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);


		            posicion_actual = 0;   // Reset position index for the next sweep
		            barrido_activo = 0;    // Disable sweep so a pending manual mode request can be applied
		            TIM4->CR1 &= ~0x0001;  // Stop TIM4
		            TIM4->CNT = 0;
		            TIM3->CR1 &= ~0x0001;  // Stop TIM3
		            TIM3->CNT = 0;
		            // Apply pending manual mode request after the sweep is finished
		            if(pendiente_manual == 1){
		            	pendiente_manual = 0;
		                modo = MANUAL;
		                GPIOA->BSRR |= (1<<(5+16));
		                sprintf(texto, "Manual\r\n");
		                HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
		            }
		        }
		    }
	        if(modo == MANUAL){

	        	valor_adc = ADC1->DR; // Read ADC value
	            int16_t angulo = (valor_adc * 180) / 4095;
	            if(angulo > angulo_anterior + 25 || angulo < angulo_anterior - 25){ // Print only when the angle variation is large enough to avoid noise-related spam
	            	angulo_anterior = angulo;
	            	sprintf(texto, "ADC: %ld, Angulo: %d\r\n", valor_adc, angulo);
	            	HAL_UART_Transmit(&huart2, (uint8_t*)texto, strlen(texto), HAL_MAX_DELAY);
	            }


	            // The potentiometer controls the servo position proportionally from 0° to 180°
	            // Add 500 because this is the minimum valid PWM compare value for the servo
	            // Scale the ADC value to the 500-2500 us servo PWM range
	            // Divide by 4095 because the ADC uses 12-bit resolution
	            TIM2->CCR1 = 500 + (valor_adc * 2000) / 4095;
	        }



	      }

  }
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL6;
  RCC_OscInitStruct.PLL.PLLDIV = RCC_PLL_DIV3;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief ADC Initialization Function
  * @param None
  * @retval None
  */
static void MX_ADC_Init(void)
{

  /* USER CODE BEGIN ADC_Init 0 */

  /* USER CODE END ADC_Init 0 */

  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC_Init 1 */

  /* USER CODE END ADC_Init 1 */

  /** Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
  */
  hadc.Instance = ADC1;
  hadc.Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV1;
  hadc.Init.Resolution = ADC_RESOLUTION_12B;
  hadc.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  hadc.Init.ScanConvMode = ADC_SCAN_DISABLE;
  hadc.Init.EOCSelection = ADC_EOC_SEQ_CONV;
  hadc.Init.LowPowerAutoWait = ADC_AUTOWAIT_DISABLE;
  hadc.Init.LowPowerAutoPowerOff = ADC_AUTOPOWEROFF_DISABLE;
  hadc.Init.ChannelsBank = ADC_CHANNELS_BANK_A;
  hadc.Init.ContinuousConvMode = DISABLE;
  hadc.Init.NbrOfConversion = 1;
  hadc.Init.DiscontinuousConvMode = DISABLE;
  hadc.Init.ExternalTrigConv = ADC_SOFTWARE_START;
  hadc.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
  hadc.Init.DMAContinuousRequests = DISABLE;
  if (HAL_ADC_Init(&hadc) != HAL_OK)
  {
    Error_Handler();
  }

  /** Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
  */
  sConfig.Channel = ADC_CHANNEL_1;
  sConfig.Rank = ADC_REGULAR_RANK_1;
  sConfig.SamplingTime = ADC_SAMPLETIME_4CYCLES;
  if (HAL_ADC_ConfigChannel(&hadc, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN ADC_Init 2 */

  /* USER CODE END ADC_Init 2 */

}

/**
  * @brief TIM2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM2_Init(void)
{

  /* USER CODE BEGIN TIM2_Init 0 */

  /* USER CODE END TIM2_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};

  /* USER CODE BEGIN TIM2_Init 1 */

  /* USER CODE END TIM2_Init 1 */
  htim2.Instance = TIM2;
  htim2.Init.Prescaler = 0;
  htim2.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim2.Init.Period = 65535;
  htim2.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim2.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim2, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  if (HAL_TIM_PWM_Init(&htim2) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim2, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 0;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&htim2, &sConfigOC, TIM_CHANNEL_1) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM2_Init 2 */

  /* USER CODE END TIM2_Init 2 */

}

/**
  * @brief TIM3 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM3_Init(void)
{

  /* USER CODE BEGIN TIM3_Init 0 */

  /* USER CODE END TIM3_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};

  /* USER CODE BEGIN TIM3_Init 1 */

  /* USER CODE END TIM3_Init 1 */
  htim3.Instance = TIM3;
  htim3.Init.Prescaler = 0;
  htim3.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim3.Init.Period = 65535;
  htim3.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim3.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim3) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim3, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim3, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM3_Init 2 */

  /* USER CODE END TIM3_Init 2 */

}

/**
  * @brief TIM4 Initialization Function
  * @param None
  * @retval None
  */
static void MX_TIM4_Init(void)
{

  /* USER CODE BEGIN TIM4_Init 0 */

  /* USER CODE END TIM4_Init 0 */

  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};

  /* USER CODE BEGIN TIM4_Init 1 */

  /* USER CODE END TIM4_Init 1 */
  htim4.Instance = TIM4;
  htim4.Init.Prescaler = 0;
  htim4.Init.CounterMode = TIM_COUNTERMODE_UP;
  htim4.Init.Period = 65535;
  htim4.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  htim4.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&htim4) != HAL_OK)
  {
    Error_Handler();
  }
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&htim4, &sClockSourceConfig) != HAL_OK)
  {
    Error_Handler();
  }
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&htim4, &sMasterConfig) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN TIM4_Init 2 */

  /* USER CODE END TIM4_Init 2 */

}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
static void MX_USART2_UART_Init(void)
{

  /* USER CODE BEGIN USART2_Init 0 */

  /* USER CODE END USART2_Init 0 */

  /* USER CODE BEGIN USART2_Init 1 */

  /* USER CODE END USART2_Init 1 */
  huart2.Instance = USART2;
  huart2.Init.BaudRate = 115200;
  huart2.Init.WordLength = UART_WORDLENGTH_8B;
  huart2.Init.StopBits = UART_STOPBITS_1;
  huart2.Init.Parity = UART_PARITY_NONE;
  huart2.Init.Mode = UART_MODE_TX_RX;
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  huart2.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
  /* USER CODE BEGIN USART2_Init 2 */

  /* USER CODE END USART2_Init 2 */

}

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};
/* USER CODE BEGIN MX_GPIO_Init_1 */

/* USER CODE END MX_GPIO_Init_1 */

  /* GPIO Ports Clock Enable */
  __HAL_RCC_GPIOC_CLK_ENABLE();
  __HAL_RCC_GPIOH_CLK_ENABLE();
  __HAL_RCC_GPIOA_CLK_ENABLE();
  __HAL_RCC_GPIOB_CLK_ENABLE();

  /*Configure GPIO pin Output Level */
  HAL_GPIO_WritePin(LD2_GPIO_Port, LD2_Pin, GPIO_PIN_RESET);

  /*Configure GPIO pin : B1_Pin */
  GPIO_InitStruct.Pin = B1_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_IT_RISING;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);

  /*Configure GPIO pin : LD2_Pin */
  GPIO_InitStruct.Pin = LD2_Pin;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init(LD2_GPIO_Port, &GPIO_InitStruct);

/* USER CODE BEGIN MX_GPIO_Init_2 */

/* USER CODE END MX_GPIO_Init_2 */
}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  (void)file;
  (void)line;
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
